const express = require('express');
const { body } = require('express-validator');
const validate = require('../middleware/validate');
const { requireAuth } = require('../middleware/auth');
const auth = require('../controllers/auth');
const projects = require('../controllers/projects');
const tasks = require('../controllers/tasks');
const router = express.Router();
const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.post('/auth/register', [body('name').isString().trim().isLength({ min: 1, max: 80 }), body('email').isEmail().normalizeEmail(), body('password').isString().isLength({ min: 8, max: 100 }), validate], asyncRoute(auth.register));
router.post('/auth/login', [body('email').isEmail().normalizeEmail(), body('password').isString().notEmpty(), validate], asyncRoute(auth.login));
router.post('/auth/logout', asyncRoute(auth.logout));
router.get('/auth/me', requireAuth, asyncRoute(auth.me));
router.put('/users/me', requireAuth, [body('name').optional().isString().trim().isLength({ min: 1, max: 80 }), body('email').optional().isEmail().normalizeEmail(), body('bio').optional().isString().isLength({ max: 500 }), validate], asyncRoute(auth.updateProfile));
router.use(requireAuth);
router.get('/projects', asyncRoute(projects.list));
router.post('/projects', [body('name').isString().trim().isLength({ min: 1, max: 100 }), body('description').optional().isString().isLength({ max: 1000 }), validate], asyncRoute(projects.create));
router.get('/projects/:projectId', asyncRoute(projects.get));
router.delete('/projects/:projectId', asyncRoute(projects.remove));
router.post('/projects/:projectId/members', [body('email').isEmail().normalizeEmail(), validate], asyncRoute(projects.addMember));
router.delete('/projects/:projectId/members/:userId', asyncRoute(projects.removeMember));
router.post('/projects/:projectId/tasks', [body('title').isString().trim().isLength({ min: 1, max: 160 }), body('description').optional().isString().isLength({ max: 3000 }), body('status').optional().isIn(['todo', 'in_progress', 'done']), body('priority').optional().isIn(['low', 'medium', 'high']), body('dueDate').optional({ values: 'null' }).isISO8601(), body('assignee').optional({ values: 'null' }).isMongoId(), validate], asyncRoute(tasks.create));
router.put('/tasks/:taskId', [body('title').optional().isString().trim().isLength({ min: 1, max: 160 }), body('description').optional().isString().isLength({ max: 3000 }), body('status').optional().isIn(['todo', 'in_progress', 'done']), body('priority').optional().isIn(['low', 'medium', 'high']), body('dueDate').optional({ values: 'null' }).isISO8601(), body('assignee').optional({ values: 'null' }).isMongoId(), validate], asyncRoute(tasks.update));
router.delete('/tasks/:taskId', asyncRoute(tasks.remove));
router.get('/tasks/:taskId/comments', asyncRoute(tasks.comments));
router.post('/tasks/:taskId/comments', [body('body').isString().trim().isLength({ min: 1, max: 2000 }), validate], asyncRoute(tasks.addComment));
router.put('/tasks/:taskId/comments/:commentId', [body('body').isString().trim().isLength({ min: 1, max: 2000 }), validate], asyncRoute(tasks.updateComment));
router.delete('/tasks/:taskId/comments/:commentId', asyncRoute(tasks.removeComment));
module.exports = router;
